name: DBT_Integration
version: 1.0.0
config-version: 2
profile: DBT_Integration
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  DBT_Integration:
    +materialized: table
seeds:
  DBT_Integration:
    +schema: dbt_sc
